<a href="https://colab.research.google.com/github/DeepandraSingh1225/Aws-ML/blob/main/day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

l = [1,2,3,4,5]
df = pd.Series(l)              # convert lis into series
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
df = pd.Series(data = l)
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
df = pd.Series(data = l, index = ['a','b','c','d','e'])
print(df)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [18]:
d = {'a':1,'b':2,'c':3,'d':4,'e':5}
df = pd.Series(d)
print(df)
print()

print(f"Element at index 'a' -> {df['a']}")

a    1
b    2
c    3
d    4
e    5
dtype: int64

Element at index 'a' -> 1

In [20]:
l = [1,2,3,4,5]
df = pd.Series(l , copy = False)

0    99
1     2
2     3
3     4
4     5
dtype: int64
[1, 2, 3, 4, 5]

In [33]:

data = {
    'name' : ['nikhil' , 'raj' , 'dev' , 'hello'],
    'age' : [10,20,30,40]
}

# 1d
df = pd.Series(data)
print(df)

# 2d
df = pd.DataFrame(data)
print(df)

name    [nikhil, raj, dev, hello]
age              [10, 20, 30, 40]
dtype: object
     name  age
0  nikhil   10
1     raj   20
2     dev   30
3   hello   40

In [42]:
data = [['nikhil' , 10] , ['raj' , 20] , ['dev' , 30] , ['hello' , 40]]
df = pd.DataFrame(data)
print(df , '\n \n')

# Add column name
df = pd.DataFrame(data , columns = ['name' , 'age'] )
print(df , '\n \n')


#Add index name
df = pd.DataFrame(data , columns = ['name' , 'age'] , index = ['a','b','c','d'])
print(df )

        0   1
0  nikhil  10
1     raj  20
2     dev  30
3   hello  40


     name  age
0  nikhil   10
1     raj   20
2     dev   30
3   hello   40


     name  age
a  nikhil   10
b     raj   20
c     dev   30
d   hello   40

##### Get file from github
##### And read as csv

In [47]:
import pandas as pd

url = 'https://raw.githubusercontent.com/DeepandraSingh1225/Aws-ML/main/file.csv'

df = pd.read_csv(url)
df

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

##### Json and Excel

In [59]:
# github json
url = "https://raw.githubusercontent.com/DeepandraSingh1225/Aws-ML/main/data.json"
df = pd.read_json(url)
print(df)
print()

       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40

In [60]:
# github excel
url = "https://raw.githubusercontent.com/DeepandraSingh1225/Aws-ML/main/file.xlsx"
df = pd.read_excel(url)
df

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

##### github csv file export

In [65]:
# github excel
url = "https://raw.githubusercontent.com/DeepandraSingh1225/Aws-ML/main/file.xlsx"
df = pd.read_excel(url)
print(df)

df.to_csv('file1.csv')

df.to_excel('file2.xlsx')

df.to_json('file3.json')

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male